# -*- coding: utf-8 -*-
"""wavlm_large_scale_7000_subset_from_asvspoof_2021.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_AjbKs8DlV0qcTo3XRozGfjo_XX-SR8
"""



"""Bismillah,

In this code, I am going to dig into ALiRAS and VGGish predictions for 7000 training and testing data, these 7000 data is the first 7000 of LA 2019 training as well as the first 7000 of 2021 evaluation sets.

# Round 2
 we made sure that the same dataset (training and testing) are used for ALiRAS, VGGish and XLSR, and HuBERT
"""





from tensorflow.keras.models import Model
from tensorflow.keras import Input
from tensorflow.keras.layers import concatenate, Permute, Reshape
import os

import math
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential

from sklearn.metrics import roc_auc_score

from imblearn.over_sampling import SMOTE

#from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM,TimeDistributed
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import sklearn.metrics as metrics

import pandas as pd
import math
import numpy as np
#from numpy.lib.function_base import average
import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import models, layers
import tensorflow as tf
from matplotlib.pyplot import specgram
import glob

from sklearn.metrics import confusion_matrix
import IPython.display as ipd  # To play sound in the notebook
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras
import sys
import warnings
# ignore warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)
import json

from sklearn.preprocessing import normalize
import warnings
warnings.filterwarnings('ignore')

import pickle
import joblib
from tensorflow.keras import models, layers
import tensorflow as tf

import pandas as pd

df_main = pd.read_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/hubert_predictions/DF_train_probs_aliras_vggish_xlsr_hubert_ensemble_7000version_matched.csv')

df_main_test = pd.read_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/hubert_predictions/DF_test_probs_aliras_vggish_xlsr_hubert_ensemble_7000version_matched.csv')

df_main

df_main_train = df_main

train_wavlm = pd.read_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/wavlm_predictions/train_predictions_wavlm_mlp_7000_df.csv')

test_wavlm = pd.read_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/wavlm_predictions/test_predictions_wavlm_mlp_7000_df.csv')

train_wavlm

train_wavlm = train_wavlm.rename(columns={'prob_spoof': 'prob_spoof_wavlm'})
test_wavlm = test_wavlm.rename(columns={'prob_spoof': 'prob_spoof_wavlm'})

test_wavlm

train_wavlm = train_wavlm.rename(columns={'audio_filenames': 'FileName'})

test_wavlm = test_wavlm.rename(columns={'audio_filenames': 'FileName'})

concatenated_df_train = df_main_train

concatenated_df_test = df_main_test

merged_df_train = pd.merge(train_wavlm, concatenated_df_train, on='FileName', how='left')

# Optional: verify result
print(merged_df_train.head())
print(f"Shape of merged dataframe: {merged_df_train.shape}")

merged_df_train

merged_df_train = merged_df_train.rename(columns={'prob_spoof_wavlm': 'prob_spoof_wavlm_mlp'})
#merged_df_test = merged_df_test.rename(columns={'prob_spoof_hubert': 'prob_spoof_hubert_resnet18'})

nan_count = merged_df_train['Label'].isna().sum()
print(f"Number of NaN values in 'Label': {nan_count}")

merged_df_train.dropna(subset=['Label'], inplace=True)

# Optional: verify result
nan_count_after = merged_df_train['Label'].isna().sum()
print(f"Number of NaN values in 'Label' after dropping: {nan_count_after}")
print(f"Shape of dataframe after dropping NaNs: {merged_df_train.shape}")

merged_df_test = pd.merge(test_wavlm, concatenated_df_test, on='FileName', how='left')

# Optional: verify result
print(merged_df_test.head())
print(f"Shape of merged dataframe: {merged_df_test.shape}")

merged_df_test

nan_count = merged_df_test['Label'].isna().sum()
print(f"Number of NaN values in 'Label': {nan_count}")

merged_df_test = merged_df_test.rename(columns={'prob_spoof_wavlm': 'prob_spoof_wavlm_mlp'})

merged_df_test

# Step 1: Create a mapping from FileName to index in concatenated_df_train
#file_to_index_map = concatenated_df_train.reset_index().set_index('FileName').index.to_series()

# Step 2: Get FileName column from merged_df_train in order
#file_names_in_merged = merged_df_train['FileName']

# Step 3: Find corresponding indexes (may contain NaN if not present)
#matching_indexes = file_names_in_merged.map(lambda x: concatenated_df_train.index[concatenated_df_train['FileName'] == x].tolist())

# Step 4: Flatten the list and handle missing
#matching_indexes_flat = [idx[0] if idx else None for idx in matching_indexes]

# Print matching indexes
#print(matching_indexes_flat)

# Filter out None (i.e., files not found in concatenated_df_train)
#valid_indexes = [idx for idx in matching_indexes_flat if idx is not None]

# Create corresponding X_train subset
#X_train_matched = X_train[valid_indexes]

# Print shape to confirm
#print(f"Shape of X_train_matched: {X_train_matched.shape}")

merged_df_test.dropna(subset=['Label'], inplace=True)

# Optional: verify result
nan_count_after = merged_df_test['Label'].isna().sum()
print(f"Number of NaN values in 'Label' after dropping: {nan_count_after}")
print(f"Shape of dataframe after dropping NaNs: {merged_df_train.shape}")

merged_df_test

"""## wavlm Metrics"""

train_probs_wavlm = merged_df_train['prob_spoof_wavlm_mlp']

test_probs_wavlm= merged_df_test['prob_spoof_wavlm_mlp']

y_train = merged_df_train['Label']

y_test = merged_df_test['Label']

roc_auc = roc_auc_score(y_train, train_probs_wavlm)

# Print the ROC AUC score
print(f"ROC AUC score for training data: {roc_auc:.4f}")

roc_auc = roc_auc_score(y_test, test_probs_wavlm)

# Print the ROC AUC score
print(f"ROC AUC score for test data: {roc_auc:.4f}")

import numpy as np
from sklearn.metrics import roc_curve

def compute_eer(y_true, y_probs):
    """
    Computes the Equal Error Rate (EER) as the average of FPR and FNR.

    Parameters:
        y_true (array-like): True binary labels (0 or 1).
        y_probs (array-like): Predicted probabilities for the positive class.

    Returns:
        eer (float): Equal Error Rate (average of FPR and FNR).
        eer_threshold (float): Threshold where FPR and FNR are closest.
    """
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, y_probs)

    # Compute False Negative Rate (FNR)
    fnr = 1 - tpr  # FNR = 1 - TPR

    # Find the threshold where FPR and FNR are closest
    eer_index = np.nanargmin(np.abs(fpr - fnr))  # Get index of min difference
    eer_threshold = thresholds[eer_index]

    # Compute EER as the average of FPR and FNR at that threshold
    eer = (fpr[eer_index] + fnr[eer_index]) / 2

    return eer, eer_threshold

from sklearn.metrics import confusion_matrix
import numpy as np

def compute_eer_fixed_threshold(y_true, y_scores, threshold):
    """
    Compute the Equal Error Rate (EER) at a fixed threshold.

    Parameters:
    - y_true: array-like of shape (n_samples,) -> True binary labels (0 or 1)
    - y_scores: array-like of shape (n_samples,) -> Predicted scores/probabilities
    - threshold: float, the fixed threshold at which to compute EER

    Returns:
    - eer: float, the average of FPR and FNR at the fixed threshold
    """
    # Convert scores to binary predictions using the fixed threshold
    y_pred = (y_scores >= threshold).astype(int)

    # Compute confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    # Compute False Positive Rate (FPR) and False Negative Rate (FNR)
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0

    # Compute EER as the average of FPR and FNR
    eer = (fpr + fnr) / 2

    return eer

eer, eer_threshold = compute_eer(y_train, train_probs_wavlm)
print(f"EER (Average of FPR & FNR): {eer:.4f}, Threshold: {eer_threshold:.4f}")

eer_test_wavlm = compute_eer_fixed_threshold(y_test, test_probs_wavlm, 0.7077)

eer_test_wavlm

"""## Ensemble (AliRAS|WavLM)"""

train_probs_aliras = merged_df_train['prob_spoof_from_aliras_mlp']
test_probs_aliras = merged_df_test['prob_spoof_from_aliras_mlp']

# Step 1: Determine the weights
weight1 = 0.7
weight2 = 0.3

# Step 2: Combine the predictions
ensemble_prediction_wavlm = (weight1 * train_probs_wavlm) + (weight2 * train_probs_aliras)

roc_auc = roc_auc_score(y_train, ensemble_prediction_wavlm)

print("ROC AUC Score:", roc_auc)

#test_probs is from vggish only
ensemble_prediction_test_wavlm = (weight1 * test_probs_wavlm) + (weight2 * test_probs_aliras)

roc_auc = roc_auc_score(y_test, ensemble_prediction_test_wavlm)

print("ROC AUC Score:", roc_auc)

compute_eer(y_train, ensemble_prediction_wavlm)

compute_eer_fixed_threshold(y_test, ensemble_prediction_test_wavlm, 0.644977305802142)

df_train_final = merged_df_train

df_test_final = merged_df_test

df_train_final['prob_spoof_from_aliras_wavlm'] =  ensemble_prediction_wavlm

df_test_final['prob_spoof_from_aliras_wavlm'] =  ensemble_prediction_test_wavlm

df_test_final

df_test_final.to_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/wavlm_predictions/DF_test_probs_aliras_vggish_xlsr_hubert_wavlm_ensemble_7000version_matched.csv', index=False)

df_train_final.to_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/wavlm_predictions/DF_train_probs_aliras_vggish_xlsr_hubert_wavlm_ensemble_7000version_matched.csv', index=False)

df_test_final

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# True labels
y_true = df_test_final['Label']

# Dictionary of models and their predicted probabilities
model_preds = {
    'XLSR-ResNet18': df_test_final['prob_spoof_from_XLSR_ResNet18'],
    'ALiRAS-MLP+VGGish-MLP': df_test_final['prob_spoof_from_aliras_vggish'],
    'ALiRAS-MLP+XLSR-ResNet18': df_test_final['prob_spoof_from_aliras_xlsr'],
    'ALiRAS-MLP': df_test_final['prob_spoof_from_aliras_mlp'],
    'VGGish-MLP': df_test_final['prob_spoof_from_vggish_mlp'],
    'HuBERT-ResNet18': df_test_final['prob_spoof_hubert_resnet18'],
    'ALiRAS-MLP+HuBERT-ResNet18': df_test_final['prob_spoof_from_aliras_hubert'],
    'WavLM-MLP': df_test_final['prob_spoof_wavlm_mlp'],
    'ALiRAS-MLP+WavLM-MLP': df_test_final['prob_spoof_from_aliras_wavlm']
}

plt.figure(figsize=(10, 8))

# Plot ROC for each model
for model_name, y_pred in model_preds.items():
    fpr, tpr, _ = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, lw=2, label=f'{model_name} (AUC = {roc_auc:.2f})')

# Plot chance line
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Chance')

# Graph formatting
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic Curves for the Test set')
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.show()

cost_efficient_wavlm_aliras_test = df_test_final.apply(
    lambda row: 1 if row['prob_spoof_from_aliras_mlp'] > 0.54 else row['prob_spoof_wavlm_mlp'],
    axis=1
)

cost_efficient_hubert_aliras_test = df_test_final.apply(
    lambda row: 1 if row['prob_spoof_from_aliras_mlp'] > 0.54 else row['prob_spoof_hubert_resnet18'],
    axis=1
)

df_test_final

cost_efficient_xlsr_aliras_test = df_test_final.apply(
    lambda row: 1 if row['prob_spoof_from_aliras_mlp'] > 0.54 else row['prob_spoof_from_XLSR_ResNet18'],
    axis=1
)

cost_efficient_wavlm_aliras_train = df_train_final.apply(
    lambda row: 1 if row['prob_spoof_from_aliras_mlp'] > 0.54 else row['prob_spoof_wavlm_mlp'],
    axis=1
)

#cost_efficient_xlsr_aliras_test = df_test_final['cost_efficient_xlsr_aliras']

roc_auc = roc_auc_score(y_train, cost_efficient_wavlm_aliras_train)

print("ROC AUC Score:", roc_auc)

roc_auc = roc_auc_score(y_test, cost_efficient_wavlm_aliras_test)

print("ROC AUC Score:", roc_auc)

cost_efficient_wavlm_aliras_train

compute_eer(y_train, cost_efficient_wavlm_aliras_train)

compute_eer_fixed_threshold(y_test, cost_efficient_wavlm_aliras_test, 0.644977305802142)

df_test_final['prob_spoof_from_aliras_wavlm_cost_efficient'] = cost_efficient_wavlm_aliras_test

df_train_final['prob_spoof_from_aliras_wavlm_cost_efficient'] = cost_efficient_wavlm_aliras_train

df_test_final['prob_spoof_from_aliras_xlsr_cost_efficient'] = cost_efficient_xlsr_aliras_test

df_test_final['cost_efficient_hubert_aliras'] = cost_efficient_hubert_aliras_test

df_test_final

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# True labels
y_true = df_test_final['Label']

# Dictionary of models and their predicted probabilities
model_preds = {
    'XLSR-ResNet18': df_test_final['prob_spoof_from_XLSR_ResNet18'],
    'ALiRAS-MLP+VGGish-MLP': df_test_final['prob_spoof_from_aliras_vggish'],
    'ALiRAS-MLP+XLSR-ResNet18': df_test_final['prob_spoof_from_aliras_xlsr'],
    'ALiRAS-MLP': df_test_final['prob_spoof_from_aliras_mlp'],
    'VGGish-MLP': df_test_final['prob_spoof_from_vggish_mlp'],
    'HuBERT-ResNet18': df_test_final['prob_spoof_hubert_resnet18'],
    'ALiRAS-MLP+HuBERT-ResNet18': df_test_final['prob_spoof_from_aliras_hubert'],
    'WavLM-MLP': df_test_final['prob_spoof_wavlm_mlp'],
    'ALiRAS-MLP+WavLM-MLP': df_test_final['prob_spoof_from_aliras_wavlm'],
    'ALiRAS-MLP+XLSR-ResNet18 (cost efficient)': df_test_final['prob_spoof_from_aliras_xlsr_cost_efficient'],
    'ALiRAS-MLP+HuBERT-ResNet18 (cost efficient)': df_test_final['cost_efficient_hubert_aliras'],
    'ALiRAS-MLP+WavLM-MLP (cost efficient)': df_test_final['prob_spoof_from_aliras_wavlm_cost_efficient']

}

plt.figure(figsize=(10, 8))

# Plot ROC for each model
for model_name, y_pred in model_preds.items():
    fpr, tpr, _ = roc_curve(y_true, y_pred)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, lw=2, label=f'{model_name} (AUC = {roc_auc:.2f})')

# Plot chance line
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', label='Chance')

# Graph formatting
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic Curves for the Test set')
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.show()

# how much cost efficient is really efficient?
count = (df_test_final['prob_spoof_from_aliras_mlp'] <= 0.54).sum()
print(f'Number of rows with prob_spoof_from_aliras_mlp which will be hubert for them < 0.54: {count}')

"""6998-4815= 2183 number of saved samples from xlsr gpu cost. In the way if aliras y_pred is more than 0.54 , then the final y_pred is 1, otherwise, we will extract the xlsr.  31% Cost/Time reduction !"""

df_test_final.to_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/wavlm_predictions/cost_efficient_DF_test_probs_aliras_vggish_xlsr_hubert_wavlm_ensemble_7000version_matched.csv', index=False)

#df_train_final.to_csv('/content/drive/MyDrive/MySelfVersionProjects/datasets/large_scale_exps_data/df_data_and_outputs/round2(all_matched_orders)/hubert_predictions/cost_efficient_DF_train_probs_aliras_vggish_xlsr_hubert_ensemble_7000version_matched.csv', index=False)